apiVersion: v1
kind: ConfigMap
metadata:
  name: dlq-config
data:
  SPRING_DATA_MONGODB_HOST: "db-dlq-book"
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: "book_dlq_db"
  SERVER_PORT: "8082"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"