apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-dlq-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-dlq-app
  template:
    metadata:
      labels:
        app: book-dlq-app
    spec:
      containers:
        - name: book-dlq-app
          image:  bookdlq:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "768Mi"   # Teto m√°ximo (se passar disso, o K8s reinicia o Pod)
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: dlq-config
            - secretRef:
                name: mongo-credentials