apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
stringData:
  SPRING_DATA_MONGODB_USERNAME: "admin"
  SPRING_DATA_MONGODB_PASSWORD: "123"
  SPRING_RABBITMQ_USERNAME: "guest"
  SPRING_RABBITMQ_PASSWORD: "guest"
