apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "book-api.fullname" . }}-app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
        - name: book-app
          image: book:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            {{ toYaml .Values.app.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "book-api.fullname" . }}-config
            - secretRef:
                name: {{ include "book-api.fullname" . }}-secret

---
apiVersion: v1
kind: Service
metadata:
  name: book-app
spec:
  type: ClusterIP
  selector:
    app: book-app
  ports:
    - port: 8080
      targetPort: 8080