apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "book-api.fullname" . }}-dlq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-dlq-app
  template:
    metadata:
      labels:
        app: book-dlq-app
    spec:
      containers:
        - name: book-dlq-app
          image: bookdlq:v1
          ports:
            - containerPort: 8082
          resources:
            {{- toYaml .Values.dlqApp.resources | nindent 12 }}

          envFrom:
            - configMapRef:
                name: {{ include "book-api.fullname" . }}-dlq-config
            - secretRef:
                name: {{ include "book-api.fullname" . }}-dlq-secret

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "book-api.fullname" . }}-dlq
spec:
  type: ClusterIP
  selector:
    app: book-dlq-app
  ports:
    - port: 8082
      targetPort: 8082