apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.scrapeInterval | quote }}
      evaluation_interval: {{ .Values.config.evaluationInterval | quote }}

    scrape_configs:
      - job_name: "api-book-service"
        metrics_path: "/actuator/prometheus"
        basic_auth:
          username: {{ .Values.config.adminUser | quote }}
          password: {{ .Values.config.adminPass | quote }}
        static_configs:
          - targets: [{{ .Values.config.bookAppTarget | quote }}]

      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]