apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus.fullname" . }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prometheus.fullname" . }}-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prometheus.fullname" . }}-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prometheus.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}