replicaCount: 1

image:
  repository: sc4rlxrd/bookdlq
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082


config:
  mongoHost: "book-system-mongo"
  mongoPort: "27017"
  mongoDatabase: "book_dlq_db"
  serverPort: "8082"
  rabbitmqHost: "book-system-rabbitmq"
  rabbitmqPort: "5672"


secret:
  mongoUser: "admin"
  mongoPass: "123"
  rabbitUser: "guest"
  rabbitPass: "guest"

resources:
  requests:
    memory: "512Mi"
    cpu: "100m"
  limits:
    memory: "768Mi"
    cpu: "500m"