apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-book.fullname" . }}
  labels:
    {{- include "app-book.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-book.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-book.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "app-book.fullname" . }}-config
            - secretRef:
                name: {{ include "app-book.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}