apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-book.fullname" . }}
spec:
  type: ClusterIP
  selector:
    {{- include "app-book.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}