apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-dlq.fullname" . }}-credentials
type: Opaque
stringData:
  SPRING_DATA_MONGODB_USERNAME: {{ .Values.secret.mongoUser | quote }}
  SPRING_DATA_MONGODB_PASSWORD: {{ .Values.secret.mongoPass | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .Values.secret.rabbitUser | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.secret.rabbitPass | quote }}