apiVersion: v1
kind: Secret
metadata:
  name: book-secret
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "root"
  SPRING_RABBITMQ_USERNAME: "guest"
  SPRING_RABBITMQ_PASSWORD: "guest"
  JWT_SECRET: "dd2e2add61a0cce0eb2bfb9c2d812515"
  ADMIN_EMAIL: "SCARLXRD@teste.com"
  ADMIN_PASSWORD: "1234569999"