replicaCount: 1

image:
  repository: "prom/prometheus"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090


config:
  scrapeInterval: "5s"
  evaluationInterval: "5s"

  bookAppTarget: "book-system-app-book:8080"
  adminUser: "admin"
  adminPass: "admin"

resources:
  requests:
    memory: "252Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "300m"