apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.dbUser | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .Values.secrets.rabbitUser | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  ADMIN_EMAIL: {{ .Values.secrets.adminEmail | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
