apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.amqpPort }}
      targetPort: {{ .Values.service.amqpPort }}
      protocol: TCP
      name: amqp
    - port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
      protocol: TCP
      name: management
    - port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
      name: metrics
      protocol: TCP
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}