apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "mongo.fullname" . }}
  selector:
    matchLabels:
      {{- include "mongo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mongo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.rootUser | quote }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.rootPassword | quote }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.database | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: mongodb
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: [ {{ .Values.persistence.accessMode | quote }} ]
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}