{{- if .Values.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.loki.service.type }}
  selector:
    app: loki
  ports:
    - port: {{ .Values.loki.service.port }}
      targetPort: {{ .Values.loki.service.port }}
{{- end }}
