enabled: true

replicaCount: 2

image:
  repository: sc4rlxrd/book
  tag: "v5"
  pullPolicy: Always

service:
  port: 8080

config:
  datasourceUrl: "jdbc:postgresql://db-book:5432/bookdb"
  rabbitmqHost: "rabbitmq"
  redisHost: "redis"
  rateLimit:
    loginAttempts: "5"
    loginTimeoutSeconds: "60"

secrets:
  dbUser: "postgres"
  dbPassword: "root"
  rabbitUser: "guest"
  rabbitPassword: "guest"
  jwtSecret: "dd2e2add61a0cce0eb2bfb9c2d812515"
  adminEmail: "SCARLXRD@teste.com"
  adminPassword: "1234569999"
  rate-limit:


resources:
  requests:
    memory: "512Mi"
    cpu: "100m"
  limits:
    memory: "768Mi"
    cpu: "500m"
