app-book:
  config:
    datasourceUrl: "jdbc:postgresql://book-system-postgres:5432/bookdb"
    rabbitmqHost: "book-system-rabbitmq"
    redisHost: "book-system-redis"
book-ingress:
  services:
    app:
      name: "book-system-app-book"
    rabbitmq:
      name: "book-system-rabbitmq"
    grafana:
      name: "book-system-grafana"

postgres:
  db:
    name: "bookdb"
